//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDinhDuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaNhanXet
    {
        public string Id { get; set; }
        public string IdUser { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public string NhanXet { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
